### Qwen3-30B-A3B 金融情感分析微调配置 (DeepSpeed ZeRO-3)
### MoE 模型虽然激活参数少，但加载时仍需 ZeRO-3 分片

### model
model_name_or_path: /home/user150/models/Qwen3-30B-A3B  # MoE 模型路径
trust_remote_code: true

### quantization (QLoRA 核心配置)
quantization_bit: 4                # 4-bit 量化，显存减少约 70%
quantization_method: bitsandbytes  # 使用 bitsandbytes 库进行量化

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target: all

### dataset
dataset: financial_sentiment_train
template: qwen3_nothink
cutoff_len: 512
max_samples: 50000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/qwen3-30b-a3b/lora/financial_sentiment_ds3
logging_steps: 10
save_steps: 500
save_total_limit: 3
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: tensorboard

### train
per_device_train_batch_size: 1  # ZeRO-3 分片后，每卡可用更大 batch
gradient_accumulation_steps: 16
learning_rate: 2.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
gradient_checkpointing: true
flash_attn: fa2
deepspeed: examples/deepspeed/ds_z3_config.json  # 启用 ZeRO-3

### eval
eval_dataset: financial_sentiment_eval
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 500
